{{- $distro := .distro -}}
{{- $suite := .suite -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install base packages
    packages:
      - init
      - initramfs-tools
      - sudo

  - action: apt
    description: Install firmwares
    packages:
{{ if eq $distro "debian" }}
      - firmware-brcm80211
      - firmware-iwlwifi
      - firmware-linux
      - firmware-realtek
{{ else if eq $distro "ubuntu" }}
      - linux-firmware
{{ end }}
  
  - action: apt
    description: Install system utilities
    packages:
      - apt-utils
      - bash-completion
      - bc
      - binutils
      - cloud-initramfs-growroot
      - curl
      - eject
      - exfat-fuse
      - file
      - gpg
      - haveged
      - htop
      - lbzip2
      - less
      - locales
      - man-db
      - nano
      - ntfs-3g
      - python3
      - python3-pip
      - software-properties-common
      - ssh
      - sysfsutils
      - tmux
      - u-boot-tools
      - vim
      - wget
      - whiptail
      - xz-utils
      - zram-tools
{{ if ne $suite "buster"}}
      - python-is-python3
      - systemd-timesyncd
{{ end }}
{{ if eq $suite "bookworm" }}
      - efibootmgr
      - systemd-boot
{{ end }}

  - action: apt
    description: Install network utilities
    packages:
      - avahi-daemon
      - bluetooth
      - dnsmasq
      - ldnsutils
      - ifupdown
      - iproute2
      - iptables
      - iputils-ping
      - iw
      - iwd
      - network-manager
      - samba
      - wireless-regdb

  - action: apt
    description: Install audio utilities
    packages:
      - alsa-utils
{{ if eq $suite "bookworm" }}
      - pipewire-audio
{{ else }}
      - pulseaudio
      - pulseaudio-module-bluetooth
{{ end }}
{{ if ne $suite "buster"}}
      - alsa-ucm-conf
{{ end }}

  - action: apt
    description: Install hardware utilities
    packages:
      - gpiod
      - hdparm
      - i2c-tools
      - mtd-utils
      - pciutils
      - rfkill
      - spi-tools
      - usbutils

{{ if eq $suite "bullseye"}}
  - action: run
    description: Installl wpasupplicant from backports
    chroot: true
    command: |
      set -e
      apt-get install -y -t {{ $suite }}-backports \
        wpasupplicant
{{ end }}

  - action: apt
    description: Install Radxa backported packages
    packages:
      - u-boot-menu

  - action: apt
    description: Install Radxa packages
    packages:
      - android-tools-adbd
      - libreelec-alsa-utils
      - radxa-bootutils
      - radxa-firmware
      - radxa-otgutils
      - radxa-udev
      - rsetup
